name: Run Selenium On GitHub Action
on:
  repository_dispatch:
    types: start-manually
  push:
  schedule:
    - cron: '30 22 * * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.6'
      - name: Installing package list
        run: apt list --installed    
      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable  
        
       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install -r requirment.txt
      - name: Install xvfb
        run: |
          wget -q -O /tmp/chrome.deb https://dl.google.com/linux/deb/pool/main/g/google-chrome-stable/google-chrome-stable_143.0.7499.40-1_amd64.deb && \
          sudo apt install -y /tmp/chrome.deb
           sudo apt-get install chromium-chromedriver
          sudo apt-get install -y xvfb


      - name: Running the Python scraper
        run: python Selenium-Template.py
      - name: Running the PythonUpdater
        run: python priceEstimator.py

      - uses: actions/checkout@v3
      - name: Commit report
        run: |
          git config --global user.name 'Mirzaei81'
          git config --global user.email 'Mirzaei81@users.noreply.github.com'
          git commit -am "Automated report"
          git push
